version: '3'
services:
  db:
    image: mysql:5.7
    container_name: money_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: money_app
    command: bash -c "rm ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/money_porter
    ports:
      - "3000:3000"
    links:
      - db
